//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedOccupancy
    {
        public long Id { get; set; }
        public long ItemID { get; set; }
        public Nullable<bool> Occupied { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
