//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long Id { get; set; }
        public long ItemID { get; set; }
        public long StoreID { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
    }
}
