//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public long Id { get; set; }
        public long InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> PaymentID { get; set; }
        public long UserId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual PatientInvoice PatientInvoice { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
