//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDefault
    {
        public long Id { get; set; }
        public long ItemID { get; set; }
        public Nullable<long> DosageId { get; set; }
        public Nullable<long> AdministrationId { get; set; }
        public Nullable<long> FrequencyId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual DrugAdministration DrugAdministration { get; set; }
        public virtual DrugDosage DrugDosage { get; set; }
        public virtual DrugFrequency DrugFrequency { get; set; }
        public virtual Item Item { get; set; }
    }
}
