//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.BedOccupancies = new HashSet<BedOccupancy>();
            this.Inventories = new HashSet<Inventory>();
            this.Item_ItemGroup = new HashSet<Item_ItemGroup>();
            this.ItemDefaults = new HashSet<ItemDefault>();
            this.ItemReorders = new HashSet<ItemReorder>();
            this.PatientServices = new HashSet<PatientService>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string GenericName { get; set; }
        public string Code { get; set; }
        public long ItemTypeId { get; set; }
        public long MedicalTypeId { get; set; }
        public long ItemCategoryId { get; set; }
        public long MeasurementUnitId { get; set; }
        public decimal SalePrice { get; set; }
        public decimal BuyPrice { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> ServiceProviderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BedOccupancy> BedOccupancies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ItemGroup> Item_ItemGroup { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDefault> ItemDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemReorder> ItemReorders { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual MedicalType MedicalType { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientService> PatientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
    }
}
