//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public long Id { get; set; }
        public long PatiendId { get; set; }
        public string ValidityPeriod { get; set; }
        public decimal AnnualFee { get; set; }
        public Nullable<bool> HealthBook { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
