//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdmission
    {
        public long Id { get; set; }
        public long PatientId { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<long> ServiceProviderId { get; set; }
        public Nullable<long> RefererId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
    }
}
