//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientService
    {
        public long Id { get; set; }
        public long PatientID { get; set; }
        public long ItemID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public decimal ServiceListPrice { get; set; }
        public decimal ServiceActualPrice { get; set; }
        public int ServiceQuantity { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> Refund { get; set; }
        public Nullable<bool> Billed { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PatientInvoice PatientInvoice { get; set; }
    }
}
