//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPayment
    {
        public long Id { get; set; }
        public long PaymentId { get; set; }
        public long ItemId { get; set; }
        public int Quantity { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
