//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.Items = new HashSet<Item>();
            this.PatientAdmissions = new HashSet<PatientAdmission>();
            this.PatientAdmissions1 = new HashSet<PatientAdmission>();
        }
    
        public long Id { get; set; }
        public long ContactId { get; set; }
        public long ServiceProviderTypeId { get; set; }
        public long DepartmentId { get; set; }
        public string Speciality { get; set; }
        public string Code { get; set; }
        public Nullable<bool> AssignedToAllUsers { get; set; }
        public Nullable<bool> IsReferer { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAdmission> PatientAdmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAdmission> PatientAdmissions1 { get; set; }
        public virtual ServiceProviderType ServiceProviderType { get; set; }
    }
}
